name: 08-runners
on:
  workflow_dispatch:

jobs:
  ######################################
  #  GITHUB (MICROSOFT) HOSTED RUNNERS
  ######################################
  #  GitHub provides hosted runners which run on Microsoft Azure.
  #  
  #  Open source projects get some free usage and pro/team/enterprise GitHub
  #  subscriptions also come with some number of minutes included (after which
  #  you pay based on usage.
  #   
  #  These are the easiest to get started with (require no additional configuration
  #  and it makes sense to use the free minutes, but only on workflows which are not in the
  #  critical path for your production deployments. For usage beyond your quota I suggest
  #  looking at the below options for higher performance (and more affordable)
  #  approaches!
  ######################################
  github-hosted-ubuntu-vm:
    name: Ubuntu 24.04 VM
    runs-on: ubuntu-24.04
    steps:
      - name: Show runner info
        run: |
          echo "Hello from ${{ runner.os }}-${{ runner.arch }}"
          echo "Runner name (type): ${{ runner.name }}"

  github-hosted-windows-vm:
    name: Windows 2022 VM
    runs-on: windows-2022
    steps:
      - name: Show runner info
        shell: pwsh
        run: |
          echo "Hello from ${{ runner.os }}-${{ runner.arch }}"
          echo "Runner name (type): ${{ runner.name }}"

  github-hosted-macos-vm:
    name: macOS 14 VM
    runs-on: macos-14
    steps:
      - name: Show runner info
        run: |
          echo "Hello from ${{ runner.os }}-${{ runner.arch }}"
          echo "Runner name (type): ${{ runner.name }}"

  alpine-container-on-github-hosted-ubuntu-vm:
    name: Alpine container on Ubuntu VM
    runs-on: ubuntu-24.04
    container:
      image: alpine:3.20
    steps:
      - name: Show runner info
        run: |
          echo "Hello from ${{ runner.os }}-${{ runner.arch }}"
          echo "Runner name (type): ${{ runner.name }}"
          echo "Container image:   $(grep PRETTY_NAME /etc/os-release)"

  