name: 09-artifacts
on:
  workflow_dispatch:

jobs:
  artifact-producer:
    name: Izveidot artifaktu
    runs-on: ubuntu-24.04
    steps:
      - name: Izveidot artifakta datni
        run: |
          echo "Šī rinda tiks ierakstīta artifakta datnē!" > artifakts.txt
          echo "Uzģenerēts darbā artifact-producer, $(date)" >> artifakts.txt

      - name: Augšupieldēt artifaktu
        uses: actions/upload-artifact@v5.0.0
        with:
          name: parauga-artifakts
          path: artifakts.txt

  artifact-consumer:
    name: Izmantot artifaktu
    runs-on: ubuntu-24.04
    needs: artifact-producer
    steps:
      - name: Lejupielādēt parauga artifaktu
        uses: actions/download-artifact@v6.0.0
        with:
          name: parauga-artifakts

      - name: Attēlot artifakta saturu
        run: cat artifakts.txt
